### ISSUE TITLE
Unable to install rh-ruby22

### ISSUE THREAD

**Issue by devsecfranklin** [da667/AutoMISP-CentOS_RHEL_Edition#2]
I had trouble during the install because the script was not able to find rh-ruby22.

Changing the package name to rh-ruby-24 fixed the issue for me. 

I think the reason is, [rh-ruby22 is not available in the Cnetos7 mirrors](http://mirror.centos.org/centos-7/7/sclo/x86_64/rh/)

(I did see rh-ruby22 in the Centos6 mirrors however)

**Comment by da667** [comment]
Very interesting.
Just verified that both CentOS7.6 on my install and RHEL7.7 both have rh-ruby22 when I requested it. 

`Package rh-ruby22-2.0-6.sc1.el7.x86_64 already installed and latest version`

Script works just fine here, but you bring up a bigger point in that at least according to the SCL group, the package has been EOL since last year. having the script grab rh-ruby24 might be a good idea simply from the standpoint of not using EOL stuff. Even though this is RHEL and CentOS we're talking about here. Judging by the fact that it worked fine for you, I'm okay with making this change.

Script has been updated. Thanks!
